// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2021 moonheart08 <moonheart08@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Rinkashikachi <15rinkashikachi15@gmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Morb <14136326+Morb0@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using Content.Shared.Administration;
using Content.Shared._AltHub.TTS; // AltHub Space
using System.Linq; // AltHub Space
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes; // AltHub Space
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!; // AltHub Space

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Announcement.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-station"));
            AnnounceMethod.SetItemMetadata(0, AdminAnnounceType.Station);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"));
            AnnounceMethod.SetItemMetadata(1, AdminAnnounceType.Server);
            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;
            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;
            // AltHub Space -> start (TTS)
            EnableTTS.OnToggled += _ => UpdateTTSControls();
            TTSVoiceButton.OnItemSelected += args =>
            {
                TTSVoiceButton.SelectId(args.Id);
            };
            PopulateTTSVoices();
            UpdateTTSControls();
            // AltHub Space -> end (TTS)
        }

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = Rope.Collapse(Announcement.TextRope).TrimStart() == "";
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            Announcer.Editable = ((AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Station) == AdminAnnounceType.Station;
        }

        // AltHub Space -> start (TTS)
        public void SetState(AdminAnnounceEuiState state)
        {
            if (state.DefaultTTSVoiceId == null)
                return;

            for (var id = 0; id < TTSVoiceButton.ItemCount; id++)
            {
                if (!Equals(TTSVoiceButton.GetItemMetadata(id), state.DefaultTTSVoiceId))
                    continue;

                TTSVoiceButton.SelectId(id);
                break;
            }
        }

        private void PopulateTTSVoices()
        {
            TTSVoiceButton.Clear();

            var voices = _prototypeManager
                .EnumeratePrototypes<TTSVoicePrototype>()
                .ToList();

            voices.Sort(static (left, right) => string.Compare(left.Name, right.Name, System.StringComparison.OrdinalIgnoreCase));

            foreach (var voice in voices)
            {
                var id = TTSVoiceButton.ItemCount;
                TTSVoiceButton.AddItem(voice.Name);
                TTSVoiceButton.SetItemMetadata(id, voice.ID);
            }

            if (TTSVoiceButton.ItemCount > 0)
                TTSVoiceButton.SelectId(0);
        }

        private void UpdateTTSControls()
        {
            var disabled = !EnableTTS.Pressed || TTSVoiceButton.ItemCount == 0;
            TTSVoiceButton.Disabled = disabled;
        }
        // AltHub Space -> end (TTS)
    }
}
