// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2021 moonheart08 <moonheart08@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Rinkashikachi <15rinkashikachi15@gmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Morb <14136326+Morb0@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using Content.Shared.Administration;
using Content.Shared._AltHub.TTS; // AltHub Space
using System.Linq; // AltHub Space
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes; // AltHub Space
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!; // AltHub Space
        private string? _defaultTTSVoiceId; // AltHub Space (TTS)

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Announcement.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-station"));
            AnnounceMethod.SetItemMetadata(0, AdminAnnounceType.Station);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"));
            AnnounceMethod.SetItemMetadata(1, AdminAnnounceType.Server);
            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;
            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;
            // AltHub Space -> start (TTS)
            EnableTTS.OnToggled += _ =>
            {
                UpdateTTSControls();
                UpdateAnnounceButton();
            };
            EnableTTSEffect.OnToggled += _ => UpdateTTSControls();
            TTSVoiceSearch.OnTextChanged += _ =>
            {
                PopulateTTSVoices();
                UpdateTTSControls();
                UpdateAnnounceButton();
            };
            ClearTTSVoiceSearch.OnPressed += _ =>
            {
                TTSVoiceSearch.Clear();
                PopulateTTSVoices();
                UpdateTTSControls();
                UpdateAnnounceButton();
            };
            TTSVoiceButton.OnItemSelected += args =>
            {
                TTSVoiceButton.SelectId(args.Id);
                UpdateAnnounceButton();
            };
            TTSEffectButton.OnItemSelected += args =>
            {
                TTSEffectButton.SelectId(args.Id);
            };
            PopulateTTSVoices();
            PopulateTTSEffects();
            UpdateTTSControls();
            // AltHub Space -> end (TTS)
        }

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            UpdateAnnounceButton();
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            Announcer.Editable = ((AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Station) == AdminAnnounceType.Station;
        }

        // AltHub Space -> start (TTS)
        public void SetState(AdminAnnounceEuiState state)
        {
            _defaultTTSVoiceId = state.DefaultTTSVoiceId;
            PopulateTTSVoices(_defaultTTSVoiceId);
            UpdateTTSControls();
            UpdateAnnounceButton();
        }

        private void PopulateTTSVoices(string? preferredVoiceId = null)
        {
            var currentVoiceId = GetSelectedTTSVoiceId();
            TTSVoiceButton.Clear();

            var voices = _prototypeManager
                .EnumeratePrototypes<TTSVoicePrototype>()
                .ToList();

            voices.Sort(static (left, right) =>
            {
                var nameCompare = string.Compare(left.Name, right.Name, System.StringComparison.OrdinalIgnoreCase);
                if (nameCompare != 0)
                    return nameCompare;

                return string.Compare(left.Source, right.Source, System.StringComparison.OrdinalIgnoreCase);
            });

            preferredVoiceId ??= currentVoiceId ?? _defaultTTSVoiceId;
            var selectedId = -1;
            var search = NormalizeTTSVoiceSearch(TTSVoiceSearch.Text);

            foreach (var voice in voices)
            {
                if (!MatchesTTSVoiceSearch(voice, search))
                    continue;

                var id = TTSVoiceButton.ItemCount;
                TTSVoiceButton.AddItem(BuildTTSVoiceLabel(voice));
                TTSVoiceButton.SetItemMetadata(id, voice.ID);

                if (voice.ID == preferredVoiceId)
                    selectedId = id;
            }

            if (TTSVoiceButton.ItemCount > 0)
                TTSVoiceButton.SelectId(selectedId >= 0 ? selectedId : 0);
        }

        private void PopulateTTSEffects()
        {
            TTSEffectButton.Clear();

            foreach (var effectId in TTSEffects.Ordered)
            {
                var id = TTSEffectButton.ItemCount;
                TTSEffectButton.AddItem(_localization.GetString($"admin-announce-tts-effect-option-{effectId}"));
                TTSEffectButton.SetItemMetadata(id, effectId);
            }

            SelectDefaultTTSEffect();
        }

        private void SelectDefaultTTSEffect()
        {
            for (var id = 0; id < TTSEffectButton.ItemCount; id++)
            {
                if (!Equals(TTSEffectButton.GetItemMetadata(id), TTSEffects.Announce))
                    continue;

                TTSEffectButton.SelectId(id);
                return;
            }

            if (TTSEffectButton.ItemCount > 0)
                TTSEffectButton.SelectId(0);
        }

        private void UpdateTTSControls()
        {
            var ttsDisabled = !EnableTTS.Pressed;
            TTSVoiceSearch.Editable = !ttsDisabled;
            ClearTTSVoiceSearch.Disabled = ttsDisabled || string.IsNullOrWhiteSpace(TTSVoiceSearch.Text);
            TTSVoiceButton.Disabled = ttsDisabled || TTSVoiceButton.ItemCount == 0;
            EnableTTSEffect.Disabled = ttsDisabled || TTSEffectButton.ItemCount == 0;
            TTSEffectButton.Disabled = ttsDisabled || !EnableTTSEffect.Pressed || TTSEffectButton.ItemCount == 0;
        }

        private void UpdateAnnounceButton()
        {
            var hasAnnouncement = Rope.Collapse(Announcement.TextRope).TrimStart() != "";
            var missingTTSVoice = EnableTTS.Pressed && TTSVoiceButton.ItemCount == 0;
            AnnounceButton.Disabled = !hasAnnouncement || missingTTSVoice;
        }

        private bool MatchesTTSVoiceSearch(TTSVoicePrototype voice, string search)
        {
            if (string.IsNullOrEmpty(search))
                return true;

            return NormalizeTTSVoiceSearch($"{voice.Name}\n{voice.Source}\n{voice.Speaker}\n{voice.Description}")
                .Contains(search, System.StringComparison.Ordinal);
        }

        private string BuildTTSVoiceLabel(TTSVoicePrototype voice)
        {
            return string.IsNullOrWhiteSpace(voice.Source)
                ? voice.Name
                : $"{voice.Name} · {voice.Source}";
        }

        private static string NormalizeTTSVoiceSearch(string? value)
        {
            return string.IsNullOrWhiteSpace(value)
                ? string.Empty
                : value.Trim().ToLowerInvariant();
        }

        public string? GetSelectedTTSVoiceId()
        {
            return TryGetSelectedOptionMetadata(TTSVoiceButton) as string;
        }

        public string? GetSelectedTTSEffectId()
        {
            return TryGetSelectedOptionMetadata(TTSEffectButton) as string;
        }

        private static object? TryGetSelectedOptionMetadata(OptionButton button)
        {
            if (button.ItemCount == 0)
                return null;

            for (var index = 0; index < button.ItemCount; index++)
            {
                if (button.GetItemId(index) == button.SelectedId)
                    return button.GetItemMetadata(index);
            }

            return null;
        }
        // AltHub Space -> end (TTS)
    }
}
